### ISSUE TITLE
renderChildren

### ISSUE THREAD

**Issue by Klabauterman** [wojtekmaj/react-calendar#2]
When using renderChildren there is still the original view visible and the return value is only appended. For example if I return "hello world" in renderChildren and i show the Month view It shows "1hello world" for the first day of the month.

**Comment by wojtekmaj** [comment]
Hello,
thank you for your report! The case you're reporting is actually by design. All calendar tiles have `<time>` element with properly set times, making it easier for visually impaired people to use React-Calendar with the help of a screen reader. Should you want to get rid of `<time>` elements, I'd suggest using CSS for that just to hide it, but not remove it entirely.

For example, if you would like to remove default <time> label for all elements that have additional content:

```css
.react-calendar__tile time:not(:last-child) {
    visibility: hidden;
    position: absolute;
    top: -9999px;
    left: -9999px;
}
```

I hope this helps!
