### ISSUE TITLE
Only show weekdays, hide weekends (5 days calendar)?

### ISSUE THREAD

**Issue by p0k8h** [wojtekmaj/react-calendar#438]
I'm not sure! Is there a config to only show weekdays for the calendar (hide weekends)which means showing 5 days calendar (Mon-Fri).

If there isn't any then, is there a way to achieve it.

Any ideas?

**Comment by wojtekmaj** [comment]
You could use `tileClassName` to pass a class name that hides a tile to weekend tiles.

Then, apply the following changes:

```css
/* Make each tile 1/5th of available space in a row, instead of default 1/7th */
.react-calendar__month-view__days > .react-calendar__tile,
.react-calendar__month-view__weekdays__weekday {
  flex-basis: 20% !important;
  max-width: 20% !important;
}

/* Hide weekday labels */
/* Variant 1 - US calendar */
.react-calendar__month-view__weekdays__weekday:nth-child(1), 
.react-calendar__month-view__weekdays__weekday:nth-child(7) {
  display: none;
}

/* Variant 2 - ISO calendar */
.react-calendar__month-view__weekdays__weekday:nth-child(6), 
.react-calendar__month-view__weekdays__weekday:nth-child(7) {
  display: none;
}
```
