### ISSUE TITLE
Calendar ShowDoubleView : for all months, the day 1 is ALWAYS a monday

### ISSUE THREAD

**Issue by lauterry** [wojtekmaj/react-calendar#482]
Hi

I have a big issue with Calendar with showDoubleView=true

```
<Calendar
	value={new Date()}
	showDoubleView
/>
```

**For all months, the day 1 is ALWAYS a monday**

<img width="830" alt="Capture d’écran 2021-02-03 à 10 40 16" src="https://user-images.githubusercontent.com/1374238/106727951-48166500-660c-11eb-9a8c-cefd715dca0a.png">

As you can see here, April 1st 2021 should be a Thursday and May 1st 2021 should be a Saturday.

This issue has been encountered in v3.3.0 and 3.3.1

Best regards

**Comment by lauterry** [comment]
It seems to be my css that causes this issue : 

```css
.date-picker-calendar-carousel {
	.react-calendar__navigation__next2-button,
	.react-calendar__navigation__prev2-button {
		display: none;
	}

	.react-calendar__viewContainer {
		display: flex;
		justify-content: space-between;
	}

	.react-calendar__month-view {
		width: 420px;
	}

	.react-calendar__month-view__days__day--neighboringMonth {
		display: none;
	}

	.react-calendar__navigation__label {
		display: flex;
		align-items: center;
		justify-content: center;
		pointer-events: none;
		background: none;
		border: none;
		outline: none;
	}

	.react-calendar__navigation {
		display: flex;
		align-items: center;
		margin-bottom: 16px;
	}

	.react-calendar__navigation__arrow {
		background: none;
		border: none;
		cursor: pointer;
		padding-left: 0;
		padding-right: 0;

		svg {
			height: 30px;
			width: 20px;
		}

		&:disabled {
			color: $grey-medium;
			cursor: not-allowed;
		}

	}

	.react-calendar__navigation__label__divider {
		display: none;
	}

	.react-calendar__navigation__label__labelText {
		@extend %font-bold;
		font-size: 18px;
		width: 50%;
	}
}
```

I have removed thoses css and the calendar is working well

<img width="825" alt="Capture d’écran 2021-02-03 à 10 59 52" src="https://user-images.githubusercontent.com/1374238/106730720-f6230e80-660e-11eb-8e4f-40bf64a9e2d8.png">


I'm still investigating which line of my css is causing this issue

**Comment by lauterry** [comment]
Ok I have found the cause of the issue : 

It is this line 

```css
.react-calendar__month-view__days__day--neighboringMonth {
	display:none;
}
```

I have follow the workaround given [here](https://github.com/wojtekmaj/react-calendar/issues/462) to remove 
neighboring months.

The fix and the correct workaround was to use visibility:hidden instead of display:none

I continue to think that in doubleViewMode, the props ```showNeighboringMonth``` should be force to false instead of true.

Best regards
