### ISSUE TITLE
Use CSS grid for rendering tile grid

### ISSUE THREAD

**Issue by caub** [wojtekmaj/react-calendar#509]
I noticed days cells are rendering using flex, and also use inline styles. This makes a large generated markup

I think css-grid would be ideal in this situation: 
![2021-04-17-110736_1346x695_scrot](https://user-images.githubusercontent.com/3134574/115107792-574f5280-9f6d-11eb-9c8c-9d7a7aac9e32.png) (check the first row, for others I didn't disable all the max-width inline styles which crops the content)

or tables for people worried about css-grid support

**Comment by wojtekmaj** [comment]
It would be wonderful and I planned this from the start, but IE support stopped me from doing it back in the days. We will need a major version bump to drop IE11 support.

**Comment by codemonkey800** [comment]
This is definitely possible if you use your own CSS:

```scss
.react-calendar__month-view__days {
  // Override react-calendar display flex styling. The library uses the
  // `style` attribute, so we need to use `!important` to override it.
  display: grid !important;

  grid-template-columns: repeat(7, 1fr);
}
```

Not sure how it'd work with the other views (century, week, etc.), but i'm sure there's some CSS you can use to get it working.
