### ISSUE TITLE
Capitalize month names in spanish language

### ISSUE THREAD

**Issue by vousys** [wojtekmaj/react-calendar#590]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Hi!, thanks for your work in this awesome project.
I saw that you use DateTimeFormat  to get the month's name. 
Can be helpful if you can capitalize the first letter of the first word, in case lang is set to "es" (spanish language).
I know that different languages, has different meaning, if you capitalize a word, but for spanish speakers is ugly to see the month name in lowercase.

This is an example:
![image](https://user-images.githubusercontent.com/12813221/153442542-ff121fc0-6551-4eef-aa52-3cac88e406d8.png)

Thanks in advance for your time.

**Comment by vousys** [comment]
Just to keep this issue open ...

**Comment by wojtekmaj** [comment]
```css
.react-calendar__navigation__label__labelText {
  display: inline-block;
}

.react-calendar__navigation__label__labelText::first-letter {
  text-transform: capitalize;
}
```
